import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Terms of Service — MMK Studios",
  description: "Terms under which you may use the MMK Studios website and AI demos.",
};

export default function TermsPage() {
  return (
    <>
      <Navbar />

      <section className="max-w-3xl mx-auto px-6 pt-20 pb-12">
        <p className="text-[#c8a86e] text-sm tracking-widest uppercase mb-4">Legal</p>
        <h1 className="font-serif text-5xl text-[#f5f0e2] mb-4">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-12">Last updated: 25 May 2026</p>

        <div className="prose prose-invert max-w-none space-y-6 text-gray-300 leading-relaxed">
          <p>
            By accessing or using this website (<strong>mmk-studios-website.vercel.app</strong>),
            you agree to be bound by these Terms of Service. If you do not agree, do not use the site.
          </p>

          <h2 className="font-serif text-2xl text-[#c8a86e] mt-10">1. Provider</h2>
          <p>
            This website is operated by <strong>Djamel Tapia</strong>, trading as
            MMK Studios, based in Madrid, Spain.
            Contact: <a href="mailto:djameltapia.dev@gmail.com" className="text-[#c8a86e] hover:underline">djameltapia.dev@gmail.com</a>.
          </p>

          <h2 className="font-serif text-2xl text-[#c8a86e] mt-10">2. Permitted use</h2>
          <p>
            You may browse the site, submit contact enquiries, and interact with our AI demos
            for personal or business evaluation purposes. You may not:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Use the site for illegal, harmful or harassing activities.</li>
            <li>Attempt to extract or reverse-engineer our underlying systems.</li>
            <li>Submit personal data of third parties without their consent.</li>
            <li>Submit copyrighted material you do not have rights to.</li>
            <li>Generate content that violates applicable law, including hate speech, violent imagery, or content involving minors.</li>
          </ul>

          <h2 className="font-serif text-2xl text-[#c8a86e] mt-10">3. AI-generated content</h2>
          <p>
            Outputs generated by our AI demos (chatbot responses, generated images)
            are produced by third-party machine-learning models. We make no warranty as to
            their accuracy, fitness for purpose, or non-infringement.
          </p>
          <p>
            You are responsible for evaluating AI outputs before using them.
            You may use generated images for personal and commercial purposes subject to
            the underlying model&apos;s license (FLUX.1 schnell: Apache 2.0).
          </p>

          <h2 className="font-serif text-2xl text-[#c8a86e] mt-10">4. Service availability</h2>
          <p>
            The site is provided &ldquo;as is&rdquo; without warranty. AI features depend on
            third-party providers (Groq, Hugging Face, Google) and may be temporarily
            unavailable.
          </p>

          <h2 className="font-serif text-2xl text-[#c8a86e] mt-10">5. Intellectual property</h2>
          <p>
            All branding, design, copy and code of this website is the property of MMK Studios,
            unless otherwise stated. AI outputs you generate are yours to use, subject to the
            model licenses referenced above.
          </p>

          <h2 className="font-serif text-2xl text-[#c8a86e] mt-10">6. Project agreements</h2>
          <p>
            Any paid services we deliver (website builds, AI integrations, automations)
            are governed by a separate written agreement covering scope, price, delivery and
            warranty. These Terms do not constitute such an agreement.
          </p>

          <h2 className="font-serif text-2xl text-[#c8a86e] mt-10">7. Limitation of liability</h2>
          <p>
            To the maximum extent permitted by Spanish law, our liability for any direct
            or indirect damages arising from your use of the site is limited to the amount
            you have paid us for our services in the 12 months preceding the event,
            or €100, whichever is lower. Nothing in these Terms limits liability that
            cannot be limited under applicable law.
          </p>

          <h2 className="font-serif text-2xl text-[#c8a86e] mt-10">8. Governing law and venue</h2>
          <p>
            These Terms are governed by Spanish law. Disputes shall be submitted to the
            courts of Madrid, Spain, except where mandatory consumer protection law provides otherwise.
          </p>

          <h2 className="font-serif text-2xl text-[#c8a86e] mt-10">9. Changes</h2>
          <p>
            We may update these Terms. Continued use of the site after a change constitutes
            acceptance of the new terms.
          </p>
        </div>
      </section>

      <Footer />
    </>
  );
}
